---
# Always submit these files to DCI:
# - Configuration files - tnf_config.yml (or certsuite_config.yml)
# - Execution logs - certsuite-stdout.log and certsuite.log, if they exist
- name: Copy config and log files related to certsuite execution
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ kbpc_log_path }}"
    mode: "0750"
  with_fileglob:
    - "{{ kbpc_certsuite_dir }}/config_files/*_config.yml"
    - "{{ kbpc_certsuite_dir }}/result_files/*.log"
  when:
    - kbpc_log_path is defined
    - kbpc_log_path|length

# Clean images just after finishing the execution
- name: Remove local certsuite image
  containers.podman.podman_image:
    name: "{{ kbpc_certsuite_image }}"
    state: absent
  ignore_errors: true

# Deleting resources created by the certsuite to support the execution
- name: Clean certsuite resources
  when: kbpc_postrun_delete_resources|bool
  block:
    - name: Define debug daemonset namespace
      ansible.builtin.set_fact:
        kbpc_debug_ds_ns: "{{ (kbpc_version == 'HEAD') | ternary('certsuite', 'cnf-suite') }}"

    - name: Ensure debug DaemonSet is absent
      vars:
        kbpc_debug_ds_name: "{{ (kbpc_version == 'HEAD') | ternary('certsuite-debug', 'tnf-debug') }}"
      community.kubernetes.k8s:
        api_version: v1
        kind: DaemonSet
        name: "{{ kbpc_debug_ds_name }}"
        namespace: "{{ kbpc_debug_ds_ns }}"
        state: absent

    - name: Ensure tnf namespace is absent
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: tnf
        state: absent

    - name: Ensure debug daemonset namespace is absent
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ kbpc_debug_ds_ns }}"
        state: absent

# This is just done when testing a certsuite stable version
- name: Delete temporary directory for git repos
  ansible.builtin.file:
    path: "{{ _kbpc_git_dir.path }}"
    state: absent
  when:
    - _kbpc_git_dir is defined
    - _kbpc_git_dir.path is defined

...
