---
- name: Fail if ecd_trex_app_version is not defined
  ansible.builtin.fail:
    msg: "ecd_trex_app_version is required"
  when: ecd_trex_app_version is not defined

- name: Get the list of incomplete jobs
  kubernetes.core.k8s_info:
    kind: Job
    api_version: batch/v1
    label_selectors:
      - example-cnf-type=pkt-gen-app
    field_selectors:
      - status.successful!=1
  register: jobs_running

- name: Set default active job fact
  ansible.builtin.set_fact:
    active_jobs: 0

- name: Find active jobs
  ansible.builtin.set_fact:
    active_jobs: "{{ active_jobs + 1 }}"
  loop: "{{ jobs_running.resources }}"
  when: "item.status.failed != 1"

- name: Fail if any one of pkt gen job is running
  ansible.builtin.fail:
    msg: "All pkt gen job should be complete before starting next"
  when: "active_jobs|int > 0"

- name: Log the test config
  ansible.builtin.debug:
    var: test_config_item

- name: Set the image name
  ansible.builtin.set_fact:
    image_app: "{{ registry_url }}/{{ repo_name }}/trex-container-app:{{ ecd_trex_app_version }}"
  when: image_app is not defined

- name: Create job for the provided test config
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'trex-app-job.yaml.j2') }}"
  vars:
    environments: "{{ test_config_item }}"
    trex_app_job_name: "{{ test_config_item.name | default('test-' + 1000 | random | string) }}"

- name: Wait for the job to complete
  kubernetes.core.k8s_info:
    kind: Job
    api_version: batch/v1
    label_selectors:
      - example-cnf-type=pkt-gen-app
    field_selectors:
      - status.successful!=1
  register: jobs_running
  retries: 120
  delay: 5
  until: jobs_running.resources|length == 0
