---
- name: "Set the MetalLB Instance"
  vars:
    instance: |-
      apiVersion: metallb.io/v1beta1
      kind: MetalLB
      metadata:
        name: "metallb"
        namespace: "{{ mlb_namespace }}"
      spec:
      {% if mlb_workers_only | default(true) | bool %}
        nodeSelector:
          node-role.kubernetes.io/worker: ""{%- endif %}
  kubernetes.core.k8s:
    state: present
    definition: "{{ instance }}"

- name: "Confirm that MetalLB speaker pods are Running"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ mlb_namespace }}"
    label_selectors:
      - component = speaker
  register: pod_list
  until: pod_list | json_query('resources[*].status.phase')|unique == ["Running"]
  retries: 18
  delay: 10
  no_log: true

- name: "Create MetalLB IP Address Pool"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: "{{ mlb_setup_name | default('metallb') }}"
        namespace: "{{ mlb_namespace }}"
      spec:
        addresses: "{{ mlb_ipaddr_pool }}"
  register: address_pool
  until: address_pool is succeeded
  retries: 6
  delay: 10
  no_log: true

- name: "Setup BGP mode objects"
  when:
    - mlb_bgp_peers is defined
  block:
    - name: "Create MetalLB BFD Profile"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: metallb.io/v1beta1
          kind: BFDProfile
          metadata:
            name: "{{ mlb_bfd_profile }}"
            namespace: "{{ mlb_namespace }}"
          spec:
            receiveInterval: 300
            transmitInterval: 300
            detectMultiplier: 3
            echoInterval: 50
            echoMode: false
            passiveMode: true
            minimumTtl: 254
      register: bfdprof
      until: bfdprof is succeeded
      retries: 6
      delay: 10
      no_log: true

    - name: "Create MetalLB BGP Peers"
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'bgppeers.yml.j2') }}"
      loop: "{{ mlb_bgp_peers }}"
      loop_control:
        loop_var: peer
      register: bgppeer
      until: bgppeer is succeeded
      retries: 6
      delay: 10
      no_log: true

    - name: "Create MetalLB BGP Advertisements"
      vars:
        bgpadvert: |-
          apiVersion: metallb.io/v1beta1
          kind: BGPAdvertisement
          metadata:
            name: "{{ mlb_setup_name | default('metallb') }}"
            namespace: "{{ mlb_namespace }}"
          spec:
            ipAddressPools:
              - "{{ mlb_setup_name | default('metallb') }}"
          {% if mlb_bgp_peers is defined %}
            peers:
          {% for peer in mlb_bgp_peers %}
              - "{{ peer.name }}"
          {% endfor %}
          {% endif %}
      kubernetes.core.k8s:
        state: present
        definition: "{{ bgpadvert }}"
      register: bgpadver
      until: bgpadver is succeeded
      retries: 6
      delay: 10
      no_log: true

- name: "Create MetalLB L2 Advertisements"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: "{{ mlb_setup_name | default('metallb') }}"
        namespace: "{{ mlb_namespace }}"
      spec:
        ipAddressPools:
          - "{{ mlb_setup_name | default('metallb') }}"
  register: l2adver
  until: l2adver is succeeded
  retries: 6
  delay: 10
  no_log: true
  when:
    - mlb_bgp_peers is undefined

- name: "Confirm that all MetalLB pods are Running"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ mlb_namespace }}"
  register: pod_list
  until: pod_list|json_query('resources[*].status.phase')|unique == ["Running"]
  retries: 9
  delay: 10
  no_log: true
...
