---
- name: "Get current worker's MCP"
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: worker
  register: worker_mcp

- name: "Get current worker's Machine config Pools"
  ansible.builtin.set_fact:
    acm_mc: "{{ worker_mcp.resources[0].spec.configuration.name }}"

- name: "Get current worker's Machine configs"
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    name: "{{ acm_mc }}"
  register: worker_mc

- name: "Get cluster user-ca cert if exists"
  kubernetes.core.k8s_info:
    api: v1
    kind: ConfigMap
    name: "user-ca-bundle"
    namespace: openshift-config
  register: user_ca_bundle

- name: "Get the user_ca_bundle content"
  ansible.builtin.set_fact:
    acm_user_ca_bundle: '{{ acm_user_bundle | default(user_ca_bundle.resources[0].data["ca-bundle.crt"]) }}'
  when:
    - user_bundle is defined or
      user_ca_bundle.resources | length == 1

- name: "Get hub cluster pull_secret details"
  kubernetes.core.k8s_info:
    api: v1
    kind: Secret
    name: "pull-secret"
    namespace: openshift-config
  register: acm_pull_secret

- name: "Setting config facts based on Hub Cluster configs"
  ansible.builtin.set_fact:
    acm_ssh_key: "{{ worker_mc.resources[0].spec.config.passwd.users[0].sshAuthorizedKeys[0] }}"
    acm_pull_secret: '{{ acm_pull_secret.resources[0].data[".dockerconfigjson"] }}'
...
