---
- name: "Fail when acm_user_registry is not defined"
  fail:
    msg: >
      acm_user_registry variable is required for disconnected environments
      Please review the example of the acm_user_registry variable in the role
      documentation
  when:
    - acm_user_registry is undefined
    - acm_disconnected | bool

- name: "Check if the ACM CRD is present"
  kubernetes.core.k8s_info:
    kind: CustomResourceDefinition
    name: multiclusterengines.multicluster.openshift.io
  register: acm_crd

- name: "Fail if ACM CRD is not present"
  fail:
    msg: "CRDs are not present"
  when: acm_crd.resources | list | count == 0

- name: "Check the AgentServiceConfig instance"
  kubernetes.core.k8s_info:
    api: agent-install.openshift.io/v1beta1
    kind: AgentServiceConfig
    name: agent
  register: _asg

- name: "Fail if AgentServiceConfig is missing"
  fail:
    msg: "An Agent Service config must be running on the Hub/Management Cluster"
  when: _asg.resources | default([]) | length == 0

- name: "Disable provisioning"
  when:
    - acm_vm_external_network | bool
  block:
    - name: "Get provisioning configuration"
      kubernetes.core.k8s_info:
        api_version: metal3.io/v1alpha1
        kind: Provisioning
        name: provisioning-configuration
      register: provisioning_cr

    - name: "Allow to expose virtual media via external network"
      kubernetes.core.k8s:
        definition:
          apiVersion: metal3.io/v1alpha1
          kind: Provisioning
          metadata:
            name: provisioning-configuration
          spec:
            virtualMediaViaExternalNetwork: true
      when:
        - provisioning_cr.resources | length
...
