---
- name: Label nodes
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'node_label.yml') | from_yaml }}"
  loop: "{{ hosts_list }}"
  loop_control:
    loop_var: inv_host
  when:
    - host_item[inv_host]['labels'] is defined
...
