---
# Always submit these files to DCI:
# - Configuration files - tnf_config.yml
# - Execution logs - dci-tnf-execution.log and cnf-certsuite.log, if exists
- name: Copy config and log files related to CNF Cert Suite execution
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ job_logs.path }}"
    mode: "0750"
  with_fileglob:
    - "{{ tnf_dir }}/{{ test_network_function_project_name }}/tnf_config.yml"
    - "{{ tnf_dir }}/{{ test_network_function_project_name }}/*.log"

# Clean images just after finishing the execution
- name: Remove local tnf image
  containers.podman.podman_image:
    name: "{{ tnf_image }}"
    state: absent
  ignore_errors: true

# Deleting resources created by the CNF Cert Suite to support the execution
- name: Clean CNF Cert Suite resources
  when: tnf_postrun_delete_resources|bool
  block:
    - name: Define tnf-debug daemonset namespace
      ansible.builtin.set_fact:
        tnf_debug_ds_ns: "cnf-suite"

    - name: Ensure tnf-debug DaemonSet is absent
      kubernetes.core.k8s:
        api_version: v1
        kind: DaemonSet
        name: tnf-debug
        namespace: "{{ tnf_debug_ds_ns }}"
        state: absent

    - name: Ensure tnf namespace is absent
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: tnf
        state: absent

    - name: Ensure tnf debug namespace is absent
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ tnf_debug_ds_ns }}"
        state: absent

# This is just done when testing a cnf-certification-test stable version
- name: Delete temporary directory for git repos
  ansible.builtin.file:
    path: "{{ tnf_git_dir.path }}"
    state: absent
  when:
    - tnf_git_dir is defined
    - tnf_git_dir.path is defined

...
