---
- name: Get Scorecard pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ preflight_namespace }}"
  register: scorecard_pods

- name: Get scorecard-related events
  kubernetes.core.k8s_info:
    kind: Event
    namespace: "{{ preflight_namespace }}"
  register: scorecard_events

- name: "Retrieve installed Subscription for {{ operator.name }}"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: "{{ operator.name }}"
  register: preflight_subs

- name: "Check CSV for {{ operator.name }}"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: "{{ operator.name }}"
  register: preflight_csv

- name: "Get events for {{ operator.name }}"
  kubernetes.core.k8s_info:
    kind: Event
    namespace: "{{ operator.name }}"
  register: preflight_events

- name: "Get pods for {{ operator.name }}"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ operator.name }}"
  register: preflight_pods

- name: "Get CatalogSource for {{ operator.name }}"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: CatalogSource
    namespace: "{{ operator.name }}"
  register: catalog_info

- name: Upload logs into DCI
  ansible.builtin.template:
    src: "templates/cluster_logs.j2"
    dest: "{{ job_logs.path }}/preflight_operator_async_{{ operator.name }}_{{ item }}.log"
    mode: "0644"

- name: Wait 50 seconds
  ansible.builtin.pause:
    seconds: 50
...
