---
- name: "Get API request counts for a workload ns {{ deprecated_ns }}"
  kubernetes.core.k8s_info:
    kind: APIRequestCount
    namespace: "{{ deprecated_ns }}"
  register: deprecated_api_apirequestcount
  no_log: true

- name: "Extract deprecated and to-be-deprecated API for {{ deprecated_ns }}"
  vars:
    query: "resources[*].{name: metadata.name, removedInRelease: status.removedInRelease}[?removedInRelease != null]"
  set_fact:
    deprecated_api_removed_api: "{{ deprecated_api_apirequestcount | json_query(query) | flatten | unique }}"

- name: "Compute OCP compatibility of the workload API for {{ deprecated_ns }}"
  vars:
    ocp_filename: "{{ deprecated_api_logs.path }}/apirequestcounts_ocp_compatibility_{{ deprecated_ns }}_junit.xml"
  set_fact:
    ocp_compatibility: "{{ deprecated_api_removed_api | redhatci.ocp.ocp_compatibility(ocp_version, ocp_filename) }}"
...
