- name: "Delete PVC used for upgrade tests"
  kubernetes.core.k8s:
    api_version: v1
    kind: PersistentVolumeClaim
    name: "{{ pvc_to_be_deleted }}"
    namespace: storage-tester
    state: absent
    wait: true
  loop:
    - storage-upgrade-tester-rwo
    - storage-upgrade-tester-rwx
    - storage-upgrade-tester-rox
  loop_control:
    loop_var: pvc_to_be_deleted

- name: "Delete storage-tester Namespace"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: storage-tester
    state: absent
    wait: true
