---
- name: Check VM config file
  ansible.builtin.stat:
    path: "{{ kvirt_vm_config_file }}"
  register: vms_conf_file_stat

- name: Fail if VM config file is not found
  ansible.builtin.fail:
    msg: "VM config file {{ kvirt_vm_config_file }} not found"
  when: not vms_conf_file_stat.stat.exists

- name: Fail VM config file is empty
  ansible.builtin.fail:
    msg: "VM config file {{ kvirt_vm_config_file }} is empty"
  when: vms_conf_file_stat.stat.size == 0

- name: Load VM config file
  ansible.builtin.include_vars:
    file: "{{ kvirt_vm_config_file }}"
  when: vms_conf_file_stat.stat.exists

- name: Fail if VM config file does not contain vm_configs
  ansible.builtin.fail:
    msg: "VM config file {{ kvirt_vm_config_file }} does not contain vm_configs"
  when: vm_configs is not defined

- name: Fail if not all VMs have a name
  ansible.builtin.fail:
    msg: "At least a VM in config file {{ kvirt_vm_config_file }} does not contain a name"
  when: vm_configs | selectattr('name', 'undefined') | list | length > 0

- name: "Get Storage Classes"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: StorageClass
  register: sc
  no_log: true

- name: "Fail when there is no storage class available"
  ansible.builtin.fail:
    msg: "A storage class does not exists"
  when:
    - sc.resources | length == 0

- name: "Fail when defined storage class does not exist"
  vars:
    query_sc_name: 'resources[*].metadata.name'
    query_results: "{{ sc | json_query(query_sc_name) }}"
  ansible.builtin.fail:
    msg: "The defined storage class does not exist"
  when:
    - kvirt_cluster_storage_class is defined
    - kvirt_cluster_storage_class not in query_results

- name: "Fail when no default storage class"
  vars:
    query_default_sc: 'resources[*].metadata.annotations."storageclass.kubernetes.io/is-default-class"'
    query_results: "{{ sc | json_query(query_default_sc) }}"
  ansible.builtin.fail:
    msg: "No default storage class was found"
  when:
    - sc is defined
    - "not('true' in query_results)"
    - kvirt_cluster_storage_class is undefined

- name: "Check if the CNV CRD is present"
  kubernetes.core.k8s_info:
    kind: CustomResourceDefinition
    name: kubevirts.kubevirt.io
  register: kvirt_crd
  no_log: true

- name: "Fail if CNV CRD is not present"
  fail:
    msg: "CRDs are not present"
  when: kvirt_crd.resources | list | count == 0
...
