---
- name: Delete Image Source from cluster
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', scorecard_is_file) }}"

- name: Wait for MCP status
  ansible.builtin.include_role:
    name: redhatci.ocp.check_resource
  vars:
    resource_to_check: "MachineConfigPool"
    check_wait_retries: 60
    check_wait_delay: 20
    check_reason: "Delete Image Sources in operator_sdk role"

- name: Remove tmp directory
  ansible.builtin.file:
    path: "{{ scorecard_tmp_dir.path }}"
    state: absent
  when: scorecard_tmp_dir is defined

- name: Remove scorecard Image Source file
  ansible.builtin.file:
    path: "{{ scorecard_is_file }}"
    state: absent
  when: scorecard_is_file is defined

- name: Remove operator_sdk_img built from the source
  ansible.builtin.command: podman rmi -f {{ operator_sdk_img }}
...
