---
- name: "Delete Logging resources"
  kubernetes.core.k8s:
    state: absent
    api: "{{ item.apiVer }}"
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"
    namespace: "{{ ol_namespace }}"
  ignore_errors: true
  loop: "{{ ol_resources }}"

- name: "Get PVCs in the namespace"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: PersistentVolumeClaim
    namespace: "{{ ol_namespace }}"
  register: pvc_info

- name: "Delete PVCs"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
      spec: {}
    state: absent
  loop: "{{ pvc_info.resources }}"
  when: pvc_info.resources | length > 0

- name: "Delete Cluster Logging namespace"
  kubernetes.core.k8s:
    state: absent
    api: "v1"
    kind: "Namespace"
    name: "{{ ol_namespace }}"
...
